CREATE TABLE PESSOA
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NOME] VARCHAR(50) NULL, 
    [CPF] VARCHAR(11) NULL, 
    [ENDERECO] NCHAR(10) NULL, 
    CONSTRAINT [FK_PESSOA_ToTable] FOREIGN KEY ([ENDERECO]) REFERENCES [ENDERECO]([Id])
	
	
);

