CREATE TABLE ENDERECO
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [LOGRADOURO] VARCHAR(256) NULL, 
    [NUMERO] INT NULL, 
    [CEP] INT NULL, 
    [BAIRRO] VARCHAR(50) NULL, 
    [CIDADE] VARCHAR(30) NULL, 
    [ESTADO] VARCHAR(20) NULL, 
   
    
)
