CREATE TABLE PESSOA
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NOME] VARCHAR(50) NULL, 
    [CPF] VARCHAR(11) NULL, 
    [ENDERECO] INTEGER NULL
	CONSTRAINT [FK_PESENDERECO] FOREIGN KEY ([ENDERECO]) REFERENCES [ENDERECO]([Id]), 
)
