CREATE TABLE [dbo].[TELEFONE]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [NUMERO] INT NULL, 
    [DDD] INT NULL, 
    [TIPO] INT NULL, 
    CONSTRAINT [FK_TELEFONE_ToTable] FOREIGN KEY ([TIPO]) REFERENCES [TELEFONE_TIPO]([ID])

)
